### PR TITLE
fix 403 and filtering when retrieving balances using the API

### PR DESCRIPTION
**Pull request by akhtariev**

### CODE REVIEW

**Comment by dhiaayachi** [comment]
Hi @akhtariev 
I did not test it for a while and I'm not able to automate testing because Newton don't offer a testing sandbox, but I will gladly review and accept PRs

**Comment by dhiaayachi** [comment]
Thank you for this change @akhtariev
  I will run the tests tonight and if everything pass I will merge it

**Comment by akhtariev** [comment]
@dhiaayachi sounds great! Thanks! I will work on some changes in the next few days then and open more PRs. I'm working on a project where I need to import  transaction data and balances so it would be great if I could just reuse this API instead of copying the logic

**Comment by akhtariev** [comment]
Awesome, thanks for reviewing and fixing the rest of the tests! Yeah, I can work on the public API this week. I will open a PR once it's ready

**Pull request merged**
